remote_theme: jekyll/minima
timezone: Canada/Eastern
logo: /assets/img/profile.jpeg
email: "contact@chaker.tech"
title: "Mohamad Jad Chaker's Personal Website"

author:
  name: "Mohamad Jad Chaker"
  email: "contact@chaker.tech"

minima:
  social_links:
    - title: "GitHub Profile"
      icon: github
      url: "https://github.com/mjchaker"
    - title: "X (Twitter) Profile"
      icon: x-twitter
      url: "https://x.com/mjchaker"

nav_pages:
  - README.md