remote_theme: jekyll/minima
timezone: Canada/Eastern
title: "Mohamad Jad Chaker"
image: "/assets/img/profile.jpeg"
logo: "/assets/img/profile.jpeg"
url: "https://mjchaker.github.io"
baseurl: ""

author:
  name: "Mohamad Jad Chaker"
  email: "contact@chaker.tech"

minima:
  social_links:
    - title: "GitHub Profile"
      icon: github
      url: "https://github.com/mjchaker"
    - title: "𝕏 (Twitter) Profile"
      icon: x-twitter
      url: "https://x.com/mjchaker"
    - title: "Threads Profile"
      icon: threads
      url: "https://www.threads.com/@mjchaker"
    - title: "Instagram Profile"
      icon: instagram
      url: "https://www.instagram.com/mjchaker/"
    - title: "Snapchat Profile"
      icon: snapchat
      url: "https://snapchat.com/t/6csaTKqZ"
    - title: "TikTok Profile"
      icon: tiktok 
      url: "https://www.tiktok.com/@mjchaker"
    - title: "Facebook Page"
      icon: facebook
      url: "https://www.facebook.com/profile.php?id=61576851823964"
    - title: "Bluesky Profile"
      icon: bluesky
      url: "https://bsky.app/profile/mjchaker.bsky.social"
    - title: "WhatsApp Business"
      icon: whatsapp
      url: "https://wa.me/17052417456"
    - title: "LinkedIn Profile"
      icon: linkedin
      url: "https://www.linkedin.com/in/mohamad-chaker-97454b1b3/"

twitter:
  username: mjchaker
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/profile.jpeg

google_analytics: G-6CHTQYN51R

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - about.md
  - projects.md
  - skills.md