remote_theme: jekyll/minima
timezone: Canada/Eastern
title: "Mohamad Jad Chaker"
dsecription: "Future engineering student at Ontario Tech University. Passionate about programming, music, and gaming."
image: "/assets/img/profile.jpeg"
logo: "/assets/img/profile.jpeg"

author:
  name: "Mohamad Jad Chaker"
  email: "contact@chaker.tech"

minima:
  social_links:
    - title: "GitHub Profile"
      icon: github
      url: "https://github.com/mjchaker"
    - title: "𝕏 (Twitter) Profile"
      icon: x-twitter
      url: "https://x.com/mjchaker"
    - title: "Threads Profile"
      icon: threads
      url: "https://www.threads.com/@mjchaker"
    - title: "Instagram Profile"
      icon: instagram
      url: "https://www.instagram.com/mjchaker/"
    - title: "Bluesky Profile"
      icon: bluesky
      url: "https://bsky.app/profile/mjchaker.bsky.social"
    - title: "Snapchat Profile"
      icon: snapchat
      url: "https://snapchat.com/t/6csaTKqZ" 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap