# ==============================================================================
# SITE CONFIGURATION
# ==============================================================================

# Theme and basic settings
remote_theme: jekyll/minima
timezone: Canada/Eastern
url: "https://mjchaker.github.io"
baseurl: ""

# Site branding and images
image: "/assets/images/profile.jpeg"
logo: "/assets/images/profile.jpeg"

# ==============================================================================
# THEME CONFIGURATION
# ==============================================================================

minima:
  skin: auto
  social_links:
    # Professional platforms
    - title: "GitHub Profile"
      icon: github
      url: "https://github.com/mjchaker"
    - title: "LinkedIn Profile"
      icon: linkedin
      url: "https://www.linkedin.com/in/mohamad-chaker-97454b1b3/"
    
    # Social media platforms
    - title: "𝕏 (Twitter) Profile"
      icon: x-twitter
      url: "https://x.com/mjchaker"
    - title: "Bluesky Profile"
      icon: bluesky
      url: "https://bsky.app/profile/mjchaker.bsky.social"
    - title: "Discord Server"
      icon: discord
      url: "https://discord.gg/zkNXckDrm3"
    - title: "Instagram Profile"
      icon: instagram
      url: "https://www.instagram.com/mjchaker/"
    - title: "Snapchat Profile"
      icon: snapchat
      url: "https://snapchat.com/t/6csaTKqZ"
    - title: "Threads Profile"
      icon: threads
      url: "https://www.threads.com/@mjchaker"
    - title: "TikTok Profile"
      icon: tiktok
      url: "https://www.tiktok.com/@mjchaker"
    - title: "YouTube Channel"
      icon: youtube
      url: "https://www.youtube.com/@mjchaker"

# ==============================================================================
# SEO AND SOCIAL MEDIA
# ==============================================================================

twitter:
  username: mjchaker
  card: summary

# Default image for all pages
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/profile.jpeg

# ==============================================================================
# ANALYTICS AND TRACKING
# ==============================================================================

google_analytics: G-6CHTQYN51R

# ==============================================================================
# PLUGINS
# ==============================================================================

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# ==============================================================================
# BLOG CONFIGURATION
# ==============================================================================

# URL structure for blog posts
permalink: /blog/:year/:month/:day/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# Excerpt settings
excerpt_separator: <!--more-->

# ==============================================================================
# CONTENT PROCESSING
# ==============================================================================

# Markdown and math settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# ==============================================================================
# NAVIGATION
# ==============================================================================

header_pages:
  - about.md
  - artistry.md
  - blog.md
  - resume.md
  - faq-page.md


# ==============================================================================
# BUILD SETTINGS
# ==============================================================================

exclude:
  - CLAUDE.md