theme: minima
title: mjchaker's homepage
description: Mohamad Jad Chaker's website.
timezone: Canada/Eastern
logo: /assets/img/profile.jpeg
name: "Mohamad Jad Chaker"
email: "contact@chaker.tech"
location: "Ontario, Canada"
university: "Ontario Tech University"
twitter_username: "mjchaker"